version: '3.4'

services:
  financialchatapi:
    image: ${DOCKER_REGISTRY-}financialchatapi
    build:
      context: .
      dockerfile: FinancialChatApi/Dockerfile

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
