version: '3.4'

services:
  financialchatapi:
    image: ${DOCKER_REGISTRY-}financialchatapi
    build:
      context: .
      dockerfile: FinancialChatApi/Dockerfile
    depends_on:
      - db    
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "AWwa45w354f0"
      ACCEPT_EULA: "Y"